#!/bin/bash
# Browser (Web Worker + MEMFS) bundle for native-wasm Wine + netduke32.
# Reuses build-node.sh's env-agnostic objects; rebuilds only wasm_ipc
# (-DWEBWINE_MEMFS) and wasm_x86 (-DWEBWINE_BROWSER).  Support objects and the
# support objects use -O3, while the browser IPC and whole-module link retain
# the measured -O1/-O3 combination; the interpreter/generated blocks and final
# browser link use -O3 for the measured browser throughput configuration.
# Prereqs: build-node.sh (OPT=-O3, XOPT=-O3) and assemble-assets.sh have run.
#   WORK=/tmp/webwine-browser ./build-browser.sh   -> $WORK/web/webwine-bw.{js,wasm,data}
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
WINE="${WINE:-$HOME/dev/wine}"; BUILD="$WINE/build-wasm4"; WEBW="$WINE/webwine"
WORK="${WORK:-/tmp/webwine-browser}"
NODEO="$WORK/nd_O3"; OUT="$WORK/web"; AT="$WORK/assets"
CINT="${CINT:--O1}"; LOPT="${LOPT:--O3}"; XOPT="${XOPT:--O3}"
source ~/dev/emsdk/emsdk_env.sh >/dev/null 2>&1
mkdir -p "$OUT"; cd "$BUILD"
[ -d "$NODEO/srv" ] || { echo "run build-node.sh (OPT=-O3, XOPT=-O3) first"; exit 1; }
[ -d "$AT/game" ]   || { echo "run assemble-assets.sh first"; exit 1; }
# AOT block translation: on when gen_blocks.c exists (build-node.sh GENBLK=1
# generated it) unless GENBLK is explicitly emptied.  Compiles the JIT into the
# browser wasm too, so the web build gets the same ~+30-45% throughput.
if [ -z "${GENBLK+x}" ] && [ -f "$WEBW/gen_blocks.c" ]; then GENBLK=1; fi
# The verified renderer FP table is generated by build-node.sh/x86toc.py.  If
# it is present, include it in normal browser bundles; runtime has an isolated
# WASM_NO_FP_HOT rollback for regressions or driver-specific differences.
if [ -z "${FP_HOT+x}" ] && [ -f "$WEBW/fp_hot_gen_blocks.c" ]; then FP_HOT=1; fi

INC="-Idlls/ntdll -I../dlls/ntdll -I../dlls/ntdll/unix -Iinclude -I../include"
CF2="-D__WINESRC__ -D_NTSYSTEM_ -D_ACRTIMP= -DWINBASEAPI= -DWINE_UNIX_LIB -fvisibility=hidden -fno-stack-protector -fno-strict-aliasing"
echo "[1/3] MEMFS ipc ($CINT) + BROWSER interpreter ($XOPT)"
emcc $CINT -DWEBWINE_MEMFS -c "$WEBW/wasm_ipc.c" -o "$NODEO/wasm_ipc_bw.o"
emcc -std=gnu23 $XOPT -DWEBWINE_BROWSER ${GENBLK:+-DWEBWINE_GENBLOCKS} ${FP_HOT:+-DWEBWINE_FP_HOT} ${PROFILE:+-DWASM_X86_PROFILE} ${MSVCRT_AOT:+-DWEBWINE_MSVCRT_AOT} ${MSVCRT_AOT_RANGE:+-DWEBWINE_MSVCRT_FOCUSED_AOT} $CF2 $INC -c "$WEBW/wasm_x86.c" -o "$NODEO/wasm_x86_bw.o"

echo "[2/3] response file"
RSP="$NODEO/objs_bw.rsp"; : > "$RSP"
echo "$NODEO/combined_main.o" >> "$RSP"; ls "$NODEO"/srv/*.o >> "$RSP"
for so in dlls/ntdll/ntdll.so dlls/win32u/win32u.so dlls/ws2_32/ws2_32.so; do echo "$so" >> "$RSP"; done
for o in wasm_cpu_bridge wasm_vm wasm_ipc_bw wasm_x86_bw; do echo "$NODEO/$o.o" >> "$RSP"; done
for o in ogl_unix_thunks ogl_unix_wgl wasm_egl_stubs; do echo "$NODEO/$o.o" >> "$RSP"; done   # opengl32 unix companion + EGL stubs

echo "[3/3] link browser bundle (worker, MEMFS, link $LOPT)"
emcc $LOPT @"$RSP" -o "$OUT/webwine-bw.js" \
  -sENVIRONMENT=worker -sFORCE_FILESYSTEM=1 \
  -sGLOBAL_BASE=1879048192 -sINITIAL_MEMORY=2147483648 -sALLOW_MEMORY_GROWTH=0 \
  -sSTACK_SIZE=67108864 -sEXIT_RUNTIME=0 \
  -lEGL -lGLESv2 -sMAX_WEBGL_VERSION=2 -sGL_ENABLE_GET_PROC_ADDRESS=1 \
  --pre-js "$HERE/bw-pre.js" \
  --preload-file "$AT/game@/game" --preload-file "$AT/root@/root"
cp "$HERE/worker.js" "$HERE/index.html" "$HERE/serve.py" "$HERE/audio-worklet.js" "$OUT/"
echo "done -> $OUT/webwine-bw.{js,wasm,data}  (+ worker.js, index.html)"
echo "serve: (cd $OUT && python3 -m http.server 8799)"
